spring:
  profiles:
    active: dev

  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      chat:
        base-url: "https://generativelanguage.googleapis.com/v1beta/openai/"
        options:
          temperature: 0.5 # 모델의 출력 다양성 조절 (0.0 ~ 1.0)
        completions-path: "/chat/completions"
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${KAKAO_OAUTH2_CLIENT_ID}
            scope: profile_nickname # 카카오 닉네임만 가져옴
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/api/{action}/oauth2/code/{registrationId}'
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            redirect-uri: '{baseUrl}/api/{action}/oauth2/code/{registrationId}'
            client-name: Google
            scope: profile
          naver:
            client-id: ${NAVER_OAUTH2_CLIENT_ID}
            client-secret: ${NAVER_OAUTH2_CLIENT_SECRET}
            scope: profile_nickname # 네이버 닉네임만 가져옴
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/api/{action}/oauth2/code/{registrationId}'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.back: DEBUG
custom:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
  accessToken:
    expirationSeconds: "#{60*20}"
server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: native
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
  base-url: "https://openapi.naver.com/v1/search/news?query="
  news:
    display: 50
    sort: sim
  crawling:
    delay: 1000 # 줄이지 말아주세요
keyword:
  overuse:
    days: 5
    threshold: 3
  history:
    recent-days: 5 # 키워드 history 조회 기준
  cleanup:
    retention-days: 5 # 키워드 history 삭제 기준
news:
  dedup:
    title:
        threshold: 0.2 # 중복 뉴스 제목 유사도 기준
    description:
        threshold: 0.15 # 중복 뉴스 내용 유사도 기준
  exclude:
    index: 1
healthchecks:
  url: ${HEALTHCHECK_URL}