spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  ai:
    openai:
      chat:
        options:
          model: "gemini-2.0-flash"

custom:
  jwt:
    secretKey: test_jwt_secret_key_for_testing_only_do_not_use_in_production
  accessToken:
    expirationSeconds: "#{60*20}"